doctrine:
    dbal:
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                charset: utf8mb4
                logging: false
                profiling: false
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

            oldversion:
                url: '%env(resolve:OLD_DATABASE_URL)%'
                charset: utf8mb4
                logging: false
                profiling: false
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
                match: Nines\UtilBundle\Extensions\Doctrine\MatchAgainst
