<?php

declare(strict_types=1);

/*
 * (c) 2021 Michael Joyce <mjoyce@sfu.ca>
 * This source file is subject to the GPL v2, bundled
 * with this source code in the file LICENSE.
 */

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Nines\UtilBundle\Entity\AbstractEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Misbehaving providers may be Blacklisted until they correct what ails them.
 *
 * @ORM\Entity(repositoryClass="App\Repository\BlacklistRepository")
 * @ORM\Table(indexes={
 *     @ORM\Index(columns={"uuid", "comment"}, flags={"fulltext"}),
 *     @ORM\Index(columns={"uuid"})
 * })
 */
class Blacklist extends AbstractEntity {
    /**
     * Provider UUID, as generated by the PLN plugin. This cannot be part
     * of a relationship - a provider may be listed before we have
     * a record of it.
     *
     * @var string
     * @Assert\Uuid(strict=false)
     * @ORM\Column(type="string", length=36, nullable=false)
     */
    private $uuid;

    /**
     * Short message describing why the provider was listed.
     *
     * @var string
     * @ORM\Column(type="text")
     */
    private $comment;

    public function __construct() {
        parent::__construct();
    }

    /**
     * The deposit's uuid is the string representation.
     */
    public function __toString() : string {
        return $this->uuid;
    }

    public function getUuid() : ?string {
        return $this->uuid;
    }

    public function setUuid(string $uuid) : self {
        $this->uuid = $uuid;

        return $this;
    }

    public function getComment() : ?string {
        return $this->comment;
    }

    public function setComment(string $comment) : self {
        $this->comment = $comment;

        return $this;
    }
}
