# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    router.request_context.scheme: '%env(string:ROUTE_PROTOCOL)%'
    router.request_context.host: '%env(string:ROUTE_HOST)%'
    router.request_context.base_url: '%env(string:ROUTE_BASE)%'

    asset.request_context.base_path: '%env(string:ROUTE_BASE)%'
    asset.request_context.secure: auto

    pln.data_dir: '%env(string:PLN_DATA_DIR)%'
    pln.clamd_socket: '%env(string:PLN_CLAMD_SOCKET)%'
    pln.uuid: '%env(string:PLN_UUID)%'
    pln.remove_completed_deposits: '%env(string:PLN_REMOVE_COMPLETE_DEPOSIT)%'
    pln.save_deposit_xml: '%env(string:PLN_SAVE_XML)%'
    pln.service_uri: '%env(string:PLN_SERVICE_URI)%'
    pln.accepting: '%env(bool:PLN_ACCEPTING)%'

    pln.network_default: The WestVault PLN does not know about this provider yet.
    pln.network_accepting: The WestVault PLN can accept deposits from this provider.

    pln.max_harvest_attempts: 5
    pln.max_au: 100000000
    pln.max_upload: 1000000
    pln.checksum_type: SHA-1

    pln.institution_name: WestVault deposits from OwnCloud

    page_size: 24

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Alias the bw server so it can be used in Twig templates.
    blackwhitelist:
        class: App\Services\BlackWhiteList

    monolog.formatter.request:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] [%%extra.ip%%] %%channel%%.%%level_name%%: %%message%%\n"

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Command\Shell\UpgradeCommand:
        arguments:
            $oldEm: '@doctrine.dbal.oldversion_connection'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments', 'knp_paginator.injectable']

    App\EventListener\SwordExceptionListener:
        arguments: ["%kernel.environment%"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
            - { name: kernel.event_listener, event: kernel.controller }

    App\EventListener\TermsOfUseListener:
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: preRemove }

    App\Logger\RequestProcessor:
        tags:
            - { name: monolog.processor }

    App\Menu\Builder:
        tags:
            - { name: knp_menu.menu_builder, method: mainMenu, alias: main}

    App\Services\FilePaths:
        arguments:
            $root: '%pln.data_dir%'
            $projectDir: '%kernel.project_dir%'

    App\Services\Processing\Harvester:
        arguments:
            $maxHarvestAttempts: '%pln.max_harvest_attempts%'

    App\Services\Processing\VirusScanner:
        arguments:
            $socketPath: '%pln.clamd_socket%'

    App\Services\Processing\StatusChecker:
        arguments:
            $cleanup: '%pln.remove_completed_deposits%'

    App\Services\SwordClient:
        arguments:
            $serviceUri: '%pln.service_uri%'
            $uuid: '%pln.uuid%'
            $saveXml: '%pln.save_deposit_xml%'
        calls:
            - [ setPlnProviderTitle, ["%pln.institution_name%"] ]
